server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO

spring:
  application:
    name: vet-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # <-- OBLIGATORIO en Render
          lower-case-service-id: true

      routes:
        # =========================================================
        # USERS SERVICE
        # =========================================================
        - id: users-service
          uri: lb://VET-USERS-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
          filters:
            - RewritePath=/api/v1/(?<remaining>.*), /api/${remaining}

        # =========================================================
        # CLINIC SERVICE
        # =========================================================
        - id: clinic-service
          uri: lb://VET-CLINIC-SERVICE
          predicates:
            - Path=/api/v1/clients/**, /api/v1/pets/**,
                   /api/v1/shifts/**, /api/v1/medical-history/**,
                   /api/v1/species/**, /api/v1/vaccines/**,
                   /api/v1/veterinarians/**, /api/v1/products/**,
                   /api/v1/suppliers/**

        # =========================================================
        # CATALOG SERVICE
        # =========================================================
        - id: catalog-service
          uri: lb://VET-CATALOG-SERVICE
          predicates:
            - Path=/api/v1/catalog/**, /graphql/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}   # <--- MUY IMPORTANTE
    preferIpAddress: false
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
